name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Backend Docker image
        run: |
          docker build \
            -t ai-secretary-backend \
            ./ai-secretary-backend

      - name: Build Frontend Docker image
        run: |
          docker build \
            -t ai-secretary-frontend \
            ./ai-secretary-frontend
